# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Hello Msci.
    echo WELCOME TO AZURE PIPELINE
  displayName: 'Run a multi-line script'
- task: BatchScript@1
  inputs:
    filename: 'hello.sh'

- script: hello.sh
  displayName: 'Run a one-line script'